#!/usr/bin/env bash
## GCP: Get crypto prices.
## Data from: binance, kraken, coinbase.
RED="\e[31m"
RC="\e[0m"
COINBASE_URL="https://api.coinbase.com/v2/prices/"
KRAKEN_URL='https://api.kraken.com/0/public/Ticker?pair='
BSCSCAN_URL='https://api.bscscan.com/api?module=stats&action=bnbprice&apikey='
## Binance Smart Chain API key, get one at https://bscscan.com/apis
BSCSCAN_API="$(cat ${HOME}/.api/bscscan.txt)"

BTC()
{
#        ## Bitcoin (data from coinbase).
#        echo "BTC: \$$(curl -s ${COINBASE_URL}BTC-USD/buy \
#        | cut -d\: -f5 \
#        | cut -d\" -f2)" \
#        | cut -d '.' -f 1

        ## Bitcoin (data from kraken).
        echo "BTC: \$$(curl -s "${KRAKEN_URL}BTCUSD" \
        | jq \
        | awk "/a/ { getline; print ${1};}" \
        | sed 's/\("\s*\|,\)//g' \
        | sed 's/ //g' \
        | cut -d '.' -f 1 )"
}

ETH()
{
#        ## Etherum (data from coinbase).
#        echo "ETH: \$$(curl -s ${COINBASE_URL}ETH-USD/buy \
#        | cut -d\: -f5 \
#        | cut -d\" -f2)" \
#        | cut -d '.' -f 1

        ## Etherum (data from kraken).
        echo "ETH: \$$(curl -s "${KRAKEN_URL}ETHUSD" \
        | jq \
        | awk "/a/ { getline; print ${1};}" \
        | sed 's/\("\s*\|,\)//g' \
        | sed 's/ //g' \
        | cut -d '.' -f 1 )"
}

XMR()
{
        ## Monero (data from kraken).
        echo "XMR: \$$(curl -s "${KRAKEN_URL}XMRUSD" \
        | jq \
        | awk "/a/ { getline; print ${1};}" \
        | sed 's/\("\s*\|,\)//g' \
        | sed 's/ //g' \
        | cut -d '.' -f 1 )"
}

BNB()
{
        ## Binance coin (Binance Smart Chain).
        echo "BNB: \$$(curl -s "${BSCSCAN_URL}${BSCSCAN_API}" \
        | cut -d ',' -f 5 \
        | cut -d : -f 2 \
        | sed 's/"//g' \
        | cut -d '.' -f 1 )"
}

REQUIREMENTS="curl perl awk sed jq"
if ! which ${REQUIREMENTS}>/dev/null
    then
        echo -e "${RED}To run this program you need: ${REQUIREMENTS}${RC}"
        exit 1
fi

BTC
ETH
XMR
BNB
